name: arculus_auth_widgets
description: Collection of theme-aware flutter auth-related widgets such as social sign in buttons, splash page, and sign in page, etc.
version: 1.0.0
repository: https://www.github.com/moseskarunia/arculus-auth-widgets

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  assets:
    - assets/
    - assets/apple_black.png
    - assets/apple_white.png
    - assets/google.png
